dtb-$(CONFIG_ARCH_SDXPOORWILLS) += sdxpoorwills-rumi.dtb \
	sdxpoorwills-cdp.dtb \
	sdxpoorwills-mtp.dtb \
	sdxpoorwills-atp.dtb \
	sdxpoorwills-ttp.dtb \
	sdxpoorwills-cdp-256.dtb \
	sdxpoorwills-mtp-256.dtb \
	sdxpoorwills-dualwifi-cdp.dtb \
	sdxpoorwills-dualwifi-mtp.dtb \
	sdxpoorwills-pcie-ep-cdp-256.dtb \
	sdxpoorwills-pcie-ep-mtp-256.dtb \
	sdxpoorwills-pcie-ep-cdp.dtb \
	sdxpoorwills-pcie-ep-mtp.dtb \
	sdxpoorwills-v2-mtp.dtb \
	sdxpoorwills-v2-cdp.dtb

dtb-$(CONFIG_ARCH_MDM9650) += mdm9650-nand-mtp.dtb \
	mdm9650-ttp.dtb \
	mdm9650-v1.1-nand-mtp.dtb \
	mdm9650-v1.1-nand-cv2x.dtb

dtb-$(CONFIG_ARCH_MDM9607) += mdm9607-mtp.dtb \
	mdm9607-ttp.dtb

# Do not include QC default DTBs if not needed
ifneq ($(CONFIG_MMI_DEVICE_DTBS),y)
dtb-$(CONFIG_ARCH_MSM8996) += msm8996-v2-pmi8994-cdp.dtb \
	msm8996-v2-pmi8994-mtp.dtb \
	msm8996-v2-pmi8994-pmk8001-cdp.dtb \
	msm8996-v2-pmi8994-pmk8001-mtp.dtb \
	msm8996-v2-pmi8994-pm8004-cdp.dtb \
	msm8996-v2-pmi8994-pm8004-mtp.dtb \
	msm8996-v2-pmi8994-pm8004-pmk8001-cdp.dtb \
	msm8996-v2-pmi8994-pm8004-pmk8001-mtp.dtb \
	msm8996-v2-fluid.dtb \
	msm8996-v2-liquid.dtb \
	msm8996-v2-dtp.dtb \
	msm8996-v3-auto-cdp.dtb \
	msm8996-v3-auto-adp.dtb \
	msm8996-v3-pmi8994-cdp.dtb \
	msm8996-v3-pmi8994-mtp.dtb \
	msm8996-v3-pmi8994-pmk8001-cdp.dtb \
	msm8996-v3-pmi8994-pmk8001-mtp.dtb \
	msm8996-v3-pmi8994-pm8004-cdp.dtb \
	msm8996-v3-pmi8994-pm8004-mtp.dtb \
	msm8996-v3-pmi8994-pm8004-pmk8001-cdp.dtb \
	msm8996-v3-pmi8994-pm8004-pmk8001-mtp.dtb \
	msm8996-v3-pmi8996-cdp.dtb \
	msm8996-v3-pmi8996-mtp.dtb \
	msm8996-v3-pmi8996-pmk8001-cdp.dtb \
	msm8996-v3-pmi8996-pmk8001-mtp.dtb \
	msm8996-v3-fluid.dtb \
	msm8996-v3-liquid.dtb \
	msm8996-v3-dtp.dtb \
	msm8996-v3-pm8004-mmxf-adp.dtb \
	msm8996-v3-pm8004-agave-adp.dtb \
	msm8996pro-auto-adp.dtb \
	msm8996pro-auto-cdp.dtb \
	msm8996pro-pmi8994-cdp.dtb \
	msm8996pro-pmi8994-mtp.dtb \
	msm8996pro-pmi8994-pmk8001-cdp.dtb \
	msm8996pro-pmi8994-pmk8001-mtp.dtb \
	msm8996pro-pmi8994-pm8004-cdp.dtb \
	msm8996pro-pmi8994-pm8004-mtp.dtb \
	msm8996pro-pmi8994-pm8004-pmk8001-cdp.dtb \
	msm8996pro-pmi8994-pm8004-pmk8001-mtp.dtb \
	msm8996pro-pmi8996-cdp.dtb \
	msm8996pro-pmi8996-mtp.dtb \
	msm8996pro-pmi8996-pmk8001-cdp.dtb \
	msm8996pro-pmi8996-pmk8001-mtp.dtb \
	msm8996pro-v1.1-auto-cdp.dtb \
	msm8996pro-v1.1-pmi8994-cdp.dtb \
	msm8996pro-v1.1-pmi8994-mtp.dtb \
	msm8996pro-v1.1-pmi8994-pmk8001-cdp.dtb \
	msm8996pro-v1.1-pmi8994-pmk8001-mtp.dtb \
	msm8996pro-v1.1-pmi8994-pm8004-cdp.dtb \
	msm8996pro-v1.1-pmi8994-pm8004-mtp.dtb \
	msm8996pro-v1.1-pmi8994-pm8004-pmk8001-cdp.dtb \
	msm8996pro-v1.1-pmi8994-pm8004-pmk8001-mtp.dtb \
	msm8996pro-v1.1-pmi8996-cdp.dtb \
	msm8996pro-v1.1-pmi8996-mtp.dtb \
	msm8996pro-v1.1-pmi8996-pmk8001-cdp.dtb \
	msm8996pro-v1.1-pmi8996-pmk8001-mtp.dtb \
	apq8096pro-auto-cdp.dtb \
	apq8096pro-liquid.dtb \
	apq8096pro-v1.1-auto-cdp.dtb \
	apq8096pro-v1.1-pmi8994-cdp.dtb \
	apq8096pro-v1.1-pmi8994-mtp.dtb \
	apq8096pro-v1.1-pmi8994-pmk8001-cdp.dtb \
	apq8096pro-v1.1-pmi8994-pmk8001-mtp.dtb \
	apq8096pro-v1.1-pmi8994-pm8004-cdp.dtb \
	apq8096pro-v1.1-pmi8994-pm8004-mtp.dtb \
	apq8096pro-v1.1-pmi8994-pm8004-pmk8001-cdp.dtb \
	apq8096pro-v1.1-pmi8994-pm8004-pmk8001-mtp.dtb \
	apq8096pro-v1.1-pmi8996-cdp.dtb \
	apq8096pro-v1.1-pmi8996-mtp.dtb \
	apq8096pro-v1.1-pmi8996-pmk8001-cdp.dtb \
	apq8096pro-v1.1-pmi8996-pmk8001-mtp.dtb \
	msm8996-v3.0-pmi8994-cdp.dtb \
	msm8996-v3.0-pmi8994-mtp.dtb \
	msm8996-v3.0-pmi8994-pm8004-cdp.dtb \
	msm8996-v3.0-pmi8994-pm8004-mtp.dtb \
	msm8996-v3.0-pmi8994-pm8004-pmk8001-cdp.dtb \
	msm8996-v3.0-pmi8994-pmk8001-cdp.dtb \
	msm8996-v3.0-pmi8996-cdp.dtb \
	msm8996-v3.0-pmi8996-mtp.dtb \
	msm8996-v3.0-fluid.dtb \
	msm8996-v3.0-liquid.dtb \
	msm8996-v3.0-dtp.dtb \
	apq8096-v2-pmi8994-cdp.dtb \
	apq8096-v2-pmi8994-mtp.dtb \
	apq8096-v2-pmi8994-pmk8001-cdp.dtb \
	apq8096-v2-pmi8994-pm8004-cdp.dtb \
	apq8096-v2-pmi8994-pm8004-pmk8001-cdp.dtb \
	apq8096-v2-liquid.dtb \
	apq8096-v2-dragonboard.dtb \
	apq8096-v2-auto-dragonboard.dtb \
	apq8096-v3-pmi8994-cdp.dtb \
	apq8096-v3-pmi8994-mtp.dtb \
	apq8096-v3-pmi8994-pmk8001-cdp.dtb \
	apq8096-v3-pmi8994-pm8004-cdp.dtb \
	apq8096-v3-pmi8994-pm8004-pmk8001-cdp.dtb \
	apq8096-v3-pmi8996-cdp.dtb \
	apq8096-v3-pmi8996-mtp.dtb \
	apq8096-v3-liquid.dtb \
	apq8096-v3-dragonboard.dtb \
	apq8096-v3-mediabox.dtb \
	apq8096-v3-sbc.dtb \
	apq8096-v3-auto-dragonboard.dtb \
	apq8096-v3-auto-adp.dtb \
	apq8096-v3-auto-cdp.dtb \
	apq8096-v3.0-pmi8994-cdp.dtb \
	apq8096-v3.0-pmi8994-mtp.dtb \
	apq8096-v3.0-pmi8994-pm8004-cdp.dtb \
	apq8096-v3.0-pmi8994-pm8004-pmk8001-cdp.dtb \
	apq8096-v3.0-pmi8994-pmk8001-cdp.dtb \
	apq8096-v3.0-pmi8996-cdp.dtb \
	apq8096-v3.0-pmi8996-mtp.dtb \
	apq8096-v3.0-liquid.dtb \
	apq8096-v3.0-dragonboard.dtb \
	apq8096-v3-pmi8994-mdm9x55-i2s-cdp.dtb \
	apq8096-v3-pmi8994-pm8004-mdm9x55-i2s-cdp.dtb \
	apq8096-v3-pmi8994-pm8004-pmk8001-mdm9x55-i2s-cdp.dtb \
	apq8096-v3-pmi8994-pmk8001-mdm9x55-i2s-cdp.dtb \
	apq8096-v3-pmi8996-mdm9x55-i2s-cdp.dtb \
	apq8096-v3-pmi8994-mdm9x55-i2s-mtp.dtb \
	apq8096-v3-pmi8994-mdm9x55-slimbus-mtp.dtb \
	apq8096-v3-pmi8996-mdm9x55-i2s-mtp.dtb \
	apq8096-v3-pmi8996-mdm9x55-slimbus-mtp.dtb \
	apq8096-v3-pmi8996-dragonboard.dtb

dtb-$(CONFIG_ARCH_MSMCOBALT) += msmcobalt-sim.dtb \
	msmcobalt-rumi.dtb \
	msmcobalt-cdp.dtb \
	msmcobalt-mtp.dtb \
	msmcobalt-v2-sim.dtb \
	msmcobalt-v2-rumi.dtb \
	msmcobalt-v2-mtp.dtb \
	msmcobalt-v2-cdp.dtb
endif # CONFIG_MMI_DEVICE_DTBS

ifeq ($(CONFIG_MMI_DEVICE_DTBS),y)
# Add 1k of padding to the DTBs to allow for environment variables
# to be runtime added by the bootloader (i.e. /chosen properties)
DTC_FLAGS := -p 1024
endif

targets += dtbs

include $(srctree)/arch/arm64/boot/dts/qcom/Makefile
$(obj)/%.dtb: $(src)/../../../../arm64/boot/dts/qcom/%.dts FORCE
	$(call if_changed_dep,dtc)

ifeq ($(CONFIG_BUILD_ARM64_DT_OVERLAY),y)
$(obj)/%.dtbo:$(src)/../../../../arm64/boot/dts/qcom/%.dts FORCE
	$(call if_changed_dep,dtc)
	$(call if_changed,dtbo_verify)

dtbs: $(addprefix $(obj)/,$(dtb-y)) $(addprefix $(obj)/,$(dtbo-y))
else
dtbs: $(addprefix $(obj)/,$(dtb-y))
endif
clean-files := *.dtb
